### ISSUE TITLE
Assets required

### ISSUE THREAD

**Issue by smileyface12349** [smileyface12349/old-fashioned-orcs#13]
Currently, the following assets are required:

- [x] A (shiny) flag
- [x] A shovel
- [x] Cave walls (could include stalactites and stalagmites)

I don't know if you can edit this to add more things or tick these off but if so please do.

**Comment by paulchen5** [comment]
can i take this?

**Comment by smileyface12349** [comment]
Sure - Ask space to see what he's done so far

**Comment by fortwoone** [comment]
I ticked what I already added. I also added stone blocks and switches (they aren't functional at the moment)
