### ISSUE TITLE
Stuck Keys

### ISSUE THREAD

**Issue by smileyface12349** [smileyface12349/old-fashioned-orcs#20]
When using WASD, some keys can get stuck down. Using arrow keys fixes it.

If this is an easy fix, then fix it. Otherwise, just tell people to use arrow keys.

**Comment by smileyface12349** [comment]
Whenever you press A or D, even after you release it you keep moving in that direction

**Comment by Nasty07** [comment]
Yeah it was buggy. I removed them completely.
