### ISSUE TITLE
Dialogue after a delay is not playing if the player moves

### ISSUE THREAD

**Issue by smileyface12349** [smileyface12349/old-fashioned-orcs#22]
The dialogue meant to trigger after a delay has stopped working for me (it used to work)

**Comment by Nasty07** [comment]
It is actually triggered if you stay still, but if you keep moving I think somehow it messes with the delay. :/

**Comment by smileyface12349** [comment]
Oh ok. Yeah this needs to be fixed

**Comment by smileyface12349** [comment]
How is it implemented?

It should be implemented such that when the requirements are met, the event triggers after the delay, regardless of if the conditions are still met in 5 seconds time.

If there's another check for if the event is satisfied, don't do that.

I can take a look at how it's working but @fortwoone do you know more about this?

**Comment by smileyface12349** [comment]
This issue is still happening. You can move away and move back again and it still works, but if you run away completely it doesn't trigger the delayed dialogue (it shouldn't be checking a second time)

**Comment by smileyface12349** [comment]
Issue resolved
