### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by smileyface12349** [smileyface12349/old-fashioned-orcs#25]
@Popaulol I saw you made some music - want to add it to the game?

**Comment by Nasty07** [comment]
We can just add a royalty free background song.

**Comment by smileyface12349** [comment]
I saw that they already made it so we might want to use it.

**Comment by Nasty07** [comment]
I don't want to be rude but, it was a retro loop that I don't believe you could listen for more than a minute.

**Comment by smileyface12349** [comment]
Yeah I guess it does get a bit repetitive, could be annoying always in the background. Let's see what other people think.

**Comment by Popaulol** [comment]
I know my stuff is really bad lol... Idk if you like it we can add it but I don't think I'll have any time to do even that myself...
I literally spent the last week doing work my parents could've gotten me last week but didn't... Why do I have to have no time in the exact week this jam is. Btw you're doing great work on the game :-)

**Comment by smileyface12349** [comment]
No it's a cool soundtrack - definitely better than I could do. It's just as a game soundtrack I wouldn't want it going on in the background for half an hour, that's all (it is quite a short loop so it gets boring fast, could work if longer though idk)

**Comment by smileyface12349** [comment]
If we want to add music (we don't have to but it could make it better) then someone could look for some royalty free tracks

**Comment by Nasty07** [comment]
Added a variety of royalty free songs for the levels, credits and main menu.
Also added a mute button in both menus.
