### ISSUE TITLE
Ending - Credits Screen etc.

### ISSUE THREAD

**Issue by smileyface12349** [smileyface12349/old-fashioned-orcs#26]
Would be nice to have a basic credits screen and possibly a menu allowing the user to go back to level 5 and try out other endings. Try to re-use dialogue things and the other menu and don't worry too much if it takes too long

**Comment by Nasty07** [comment]
We can simply create an image, like the "error occurred" one, to show as credits after completing the last level.
The player can join back to the last level anyway, if he goes back to the menu and hit play once again.
