### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by smileyface12349** [smileyface12349/old-fashioned-orcs#5]
This comes in two stages:

1) Decide on how exactly WebSockets will be used in the game. Will they be just to enable multiplayer? If so, how will this work and how will it benefit the game?

2) Implement a way of handling WebSockets in accordance with step 1 in a way that can be easily accessed in the rest of the code

**Comment by Nasty07** [comment]
How about using a WebSocket for each player's session all the time?
So that, in order to play the game you must connect to the server.

**Comment by fortwoone** [comment]
I do think that's a good idea

**Comment by fortwoone** [comment]
Except for the tutorial level, which should not be connected to the server in order to not distract the player from the explanations

**Comment by Nasty07** [comment]
So we can make an endpoint like /connect that the player will hit when pressing the Start/Play button that creates a WebSocket which will handle the whole process, from basic stuff like assigning a unique id and saving progress in someway up to enabling multiplayer view or letting players interact with each other (if we want to). 

Tutorial can be a completely separate function/button.

**Comment by Nasty07** [comment]
We also need to find a way to handle freezes, high latency and short disconnects before forcing the player to exit/reset to main menu.

**Comment by smileyface12349** [comment]
> Except for the tutorial level, which should not be connected to the server in order to not distract the player from the explanations

I don't think we need a tutorial level - a quick indication that it's WASD to move and E to interact (or whatever the controls are) would be fine, it won't be that complicated.

**Comment by fortwoone** [comment]
I actually thought about the tutorial to teach the players that some things can be "glitched" and that they should use that

**Comment by smileyface12349** [comment]
I think it would be cooler to have dialogue e.g. "This is a wall. Just a large brick wall. Of course you can't go through it - It's a wall" that tells the player what they can do without actually directly telling them.

Just made me think we could have the character talking to another character through a brick (fake) wall and when the player doesn't cooperate (e.g. when given an impossible task) they could claim it's like "talking to a brick wall". Maybe that was funnier in my head lol. If that's a British phrase, then just put something onscreen saying that it's a British thing and I promise it's funny.

**Comment by smileyface12349** [comment]
Teaching the player without taking them out of the game though is always better and more immersive (if done right)

**Comment by fortwoone** [comment]
Well, in fact my original idea was to have an ironic title like "A Totally Generic Platformer", and the tutorial guy would be all like "I suppose I don't need to tell you how to move since you chose the controls yourself", and stay into that "break the 4th wall" idea

**Comment by smileyface12349** [comment]
Yeah that sounds great - as long as it's not a boring tutorial that just tells you all the controls and all the different things you can do without being able to figure them out yourself

**Comment by smileyface12349** [comment]
Is this now done?

**Comment by Nasty07** [comment]
Yeap, client/server things work as expected.
Everything is ready.
