### ISSUE TITLE
General Design

### ISSUE THREAD

**Issue by smileyface12349** [smileyface12349/old-fashioned-orcs#6]
We still need a bit more planning on how the whole thing will work. What's the game actually about? How are we going to implement it?

I'm happy to do some of this but I think this is naturally suited to a team effort so we can use lots of different ideas.

**Comment by smileyface12349** [comment]
Okay so the frontend will be done in PyGame. This will the interface with the server through WebSockets.

Exactly what information is being transferred to and from the server is yet to be decided

**Comment by Nasty07** [comment]
We can start with some basics like:

1. Players' nicknames,
2. some kind of unique identifier,
3. their position in map,
4. their current level,
5. their connection status
