### ISSUE TITLE
Dialogue

### ISSUE THREAD

**Issue by smileyface12349** [smileyface12349/old-fashioned-orcs#9]
There needs to be a system to display text onscreen (just a box with text in it is fine).

The text to be displayed would be stored somewhere and it would be triggered by certain events. The user can press a button to advance to the next line of dialogue.

**Comment by smileyface12349** [comment]
I don't think dialogue options are needed as of yet but they would be helpful (this will depend on level design)

**Comment by smileyface12349** [comment]
How's this going?

**Comment by Nasty07** [comment]
If I'm not mistaken, dialogue events work now.
